### ISSUE TITLE
 css, JavaScript Don't work  ,Lesson four  

### ISSUE THREAD

**Issue by AttSee** [thewhitetulip/write-webapps-in-go-video#1]
Hi again
What is the problem ?
 css, JavaScript Don't work  ?

here exp
[exp0.zip](https://github.com/thewhitetulip/write-webapps-in-go-video/files/932174/exp0.zip)

**Comment by AttSee** [comment]
I don't know if I'm in the right place.
 (:

**Comment by thewhitetulip** [comment]
What branch are you on? Pls don't upload zip files.

**Comment by AttSee** [comment]
sorry
here
[exp.tar.gz](https://github.com/thewhitetulip/write-webapps-in-go-video/files/954967/exp.tar.gz)
![screenshot from 2017-04-25 14-26-47]


![screenshot from 2017-04-25 15-08-08](https://cloud.githubusercontent.com/assets/22094152/25386851/0a12b160-29c9-11e7-9366-3b325e2a803b.png)

**Comment by thewhitetulip** [comment]
Dude, that's what I asked, which branch are you on? I can't download a zip, it would be great if you create a gist.

Also, do you have a question on your code or the code you found in this repo? If you have a different question you can email me rather than discussing here, because this issue tracker is related to bugs in the repo and not for personal doubts :)
